language: node_js
sudo: false
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '4'
  - '5'
  - '6'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower grunt-cli
  - npm i -g polylint@v2.9.1
  - bower i
script:
  - ./travis-runner.sh
env:
  global:
    - "CXX='g++-4.8'"