language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
  - '5'
  - '4'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g bower polymer-cli
  - npm install
  - bower install
script:
  - xvfb-run polymer test
env:
  global:
    - "CXX='g++-4.8'"
